const blackjackDeck = 
[
  { title: 'Ah', value: 11 },
  { title: 'Ad', value: 11 },
  { title: 'As', value: 11 },
  { title: 'Ac', value: 11 },
  { title: '2h', value: 2 },
  { title: '2d', value: 2 },
  { title: '2s', value: 2 },
  { title: '2c', value: 2 },
  { title: '3h', value: 3 },
  { title: '3d', value: 3 },
  { title: '3s', value: 3 },
  { title: '3c', value: 3 },
  { title: '4h', value: 4 },
  { title: '4d', value: 4 },
  { title: '4s', value: 4 },
  { title: '4c', value: 4 },
  { title: '5h', value: 5 },
  { title: '5d', value: 5 },
  { title: '5s', value: 5 },
  { title: '5c', value: 5 },
  { title: '6h', value: 6 },
  { title: '6d', value: 6 },
  { title: '6s', value: 6 },
  { title: '6c', value: 6 },
  { title: '7h', value: 7 },
  { title: '7d', value: 7 },
  { title: '7s', value: 7 },
  { title: '7c', value: 7 },
  { title: '8h', value: 8 },
  { title: '8d', value: 8 },
  { title: '8s', value: 8 },
  { title: '8c', value: 8 },
  { title: '9h', value: 9 },
  { title: '9d', value: 9 },
  { title: '9s', value: 9 },
  { title: '9c', value: 9 },
  { title: 'Th', value: 10 },
  { title: 'Td', value: 10 },
  { title: 'Ts', value: 10 },
  { title: 'Tc', value: 10 },
  { title: 'Jh', value: 10 },
  { title: 'Jd', value: 10 },
  { title: 'Js', value: 10 },
  { title: 'Jc', value: 10 },
  { title: 'Qh', value: 10 },
  { title: 'Qd', value: 10 },
  { title: 'Qs', value: 10 },
  { title: 'Qc', value: 10 },
  { title: 'Kh', value: 10 },
  { title: 'Kd', value: 10 },
  { title: 'Ks', value: 10 },
  { title: 'Kc', value: 10 }
];

const sort = (title1, title2) => Math.round(Math.random()) === 0 ? 1 : -1;

export let shuffleBJDeck = () => blackjackDeck.sort(sort).sort(sort);

